# Generated by Django 3.1.7 on 2021-03-17 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentfood', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='mark',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='on_favorite',
        ),
    ]
