# Generated by Django 3.0.5 on 2021-05-24 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentfood', '0002_auto_20210511_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='recipe_img', verbose_name='Фото рецепта'),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(default='media/user_img/no_photo.jpg', upload_to='user_img', verbose_name='Фото'),
        ),
    ]
