# Generated by Django 3.1.7 on 2021-05-28 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentfood', '0002_auto_20210525_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='is_removed',
            field=models.BooleanField(default=False, verbose_name='Статус удаления'),
        ),
    ]
