# Generated by Django 3.1.7 on 2021-05-04 15:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('studentfood', '0003_recipe_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 4, 15, 49, 40, 179605, tzinfo=utc), verbose_name='Опубликовано'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.CharField(max_length=1500, verbose_name='Текст комментария'),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(null=True, upload_to='', verbose_name='Фото'),
        ),
    ]
