# Generated by Django 3.1.7 on 2021-05-11 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentfood', '0006_auto_20210505_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='save_recipe_photo/', verbose_name='Фото рецепта'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации'),
        ),
    ]
