# Generated by Django 3.1.7 on 2021-05-23 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentfood', '0008_auto_20210522_0549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='recipe_img', verbose_name='Фото рецепта'),
        ),
    ]
