# Generated by Django 3.1.7 on 2021-05-23 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentfood', '0009_auto_20210523_0828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(default='media/user_img/no_photo.jpg', upload_to='user_img', verbose_name='Фото'),
        ),
    ]
