# Generated by Django 3.1.7 on 2021-05-25 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentfood', '0003_auto_20210524_1942'),
        ('studentfood', '0011_auto_20210524_1035'),
    ]

    operations = [
    ]
